In [69]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

READ AND PREPROCESS DATA

In [36]:
df =pd.read_csv("output.csv")

In [37]:
df.head()

   Bot_Cell Crew_Cell
0  (10, 10)   (10, 8)
1   (10, 9)    (9, 8)
2    (9, 9)    (9, 7)
3    (9, 8)    (8, 7)
4    (9, 7)    (7, 7)

In [38]:
# Extract x, y, p, and q values from the existing columns
df['x'] = df['Bot_Cell'].apply(lambda x: int(x.split(',')[0].strip('()')))
df['y'] = df['Bot_Cell'].apply(lambda x: int(x.split(',')[1].strip('()')))
df['p'] = df['Crew_Cell'].apply(lambda x: int(x.split(',')[0].strip('()')))
df['q'] = df['Crew_Cell'].apply(lambda x: int(x.split(',')[1].strip('()')))

# Calculate the distance
df['Distance_from_bot_to_crew'] = abs(df['x'] - df['p']) + abs(df['y'] - df['q'])
df['Distance_from_bot_to_teleport'] = abs(df['x'] - 5) + abs(df['y'] - 5)
df['Distance_from_crew_to_teleport'] = abs(5 - df['p']) + abs(5 - df['q'])
#Drop the intermediate columns x, y, p, and q if needed
df.drop(['x', 'y', 'p', 'q'], axis=1, inplace=True)

In [39]:
df['Bot_Move'] = df['Bot_Cell'].shift(-1)

In [40]:
df.head()

   Bot_Cell Crew_Cell  Distance_from_bot_to_crew Bot_Move
0  (10, 10)   (10, 8)                          2  (10, 9)
1   (10, 9)    (9, 8)                          2   (9, 9)
2    (9, 9)    (9, 7)                          2   (9, 8)
3    (9, 8)    (8, 7)                          2   (9, 7)
4    (9, 7)    (7, 7)                          2   (8, 7)

Encodding the data

In [41]:
one_hot_encoded_df = df.copy()
one_hot_encoded_df = pd.get_dummies(df)
one_hot_encoded_df.head()

,Distance_from_bot_to_crew,"Bot_Cell_(10, 10)","Bot_Cell_(10, 6)","Bot_Cell_(10, 7)","Bot_Cell_(10, 8)","Bot_Cell_(10, 9)","Bot_Cell_(5, 10)","Bot_Cell_(5, 9)","Bot_Cell_(6, 10)","Bot_Cell_(6, 8)",...,"Bot_Move_(8, 4)","Bot_Move_(8, 5)","Bot_Move_(8, 6)","Bot_Move_(8, 7)","Bot_Move_(8, 8)","Bot_Move_(8, 9)","Bot_Move_(9, 6)","Bot_Move_(9, 7)","Bot_Move_(9, 8)","Bot_Move_(9, 9)"
0,2,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,2,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [42]:
label_encoder = LabelEncoder()
label_encoded_df = df.copy()
# Iterate over each column in the DataFrame
for column in label_encoded_df.columns:
    # Check if the column is categorical (i.e., dtype is object)
    if label_encoded_df[column].dtype == 'object':
        # Fit label encoder and transform values for the current column
        label_encoded_df[column] = label_encoder.fit_transform(label_encoded_df[column])

In [43]:
label_encoded_df.head()

   Bot_Cell  Crew_Cell  Distance_from_bot_to_crew  Bot_Move
0         0          2                          2         4
1         4         25                          2        25
2        25         24                          2        24
3        24         20                          2        23
4        23         15                          2        19

In [52]:

correlation_matrix1 = label_encoded_df.corr()
correlation_matrix2 = one_hot_encoded_df.corr()

In [50]:
correlation_matrix1

,Bot_Cell,Crew_Cell,Distance_from_bot_to_crew,Bot_Move
Bot_Cell,1.000000,0.010635,NaN,0.469975
Crew_Cell,0.010635,1.000000,NaN,0.478612
Distance_from_bot_to_crew,NaN,NaN,NaN,NaN
Bot_Move,0.469975,0.478612,NaN,1.000000

In [49]:
correlation_matrix2

,Distance_from_bot_to_crew,"Bot_Cell_(10, 10)","Bot_Cell_(10, 6)","Bot_Cell_(10, 7)","Bot_Cell_(10, 8)","Bot_Cell_(10, 9)","Bot_Cell_(5, 10)","Bot_Cell_(5, 9)","Bot_Cell_(6, 10)","Bot_Cell_(6, 8)",...,"Bot_Move_(8, 4)","Bot_Move_(8, 5)","Bot_Move_(8, 6)","Bot_Move_(8, 7)","Bot_Move_(8, 8)","Bot_Move_(8, 9)","Bot_Move_(9, 6)","Bot_Move_(9, 7)","Bot_Move_(9, 8)","Bot_Move_(9, 9)"
Distance_from_bot_to_crew,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Bot_Cell_(10, 10)",NaN,1.000000,-0.037037,-0.045787,-0.037037,-0.045787,-0.025950,-0.025950,-0.025950,-0.025950,...,-0.037037,-0.053376,-0.045787,-0.037037,-0.053376,-0.037037,-0.025950,-0.037037,-0.053376,-0.045787
"Bot_Cell_(10, 6)",NaN,-0.037037,1.000000,-0.045787,-0.037037,-0.045787,-0.025950,-0.025950,-0.025950,-0.025950,...,-0.037037,-0.053376,-0.045787,-0.037037,-0.053376,-0.037037,0.700649,-0.037037,-0.053376,-0.045787
"Bot_Cell_(10, 7)",NaN,-0.045787,-0.045787,1.000000,-0.045787,-0.056604,-0.032081,-0.032081,-0.032081,-0.032081,...,-0.045787,-0.065986,-0.056604,-0.045787,-0.065986,-0.045787,-0.032081,-0.045787,-0.065986,-0.056604
"Bot_Cell_(10, 8)",NaN,-0.037037,-0.037037,-0.045787,1.000000,-0.045787,-0.025950,-0.025950,-0.025950,-0.025950,...,-0.037037,-0.053376,-0.045787,-0.037037,-0.053376,-0.037037,-0.025950,-0.037037,-0.053376,-0.045787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Bot_Move_(8, 9)",NaN,-0.037037,-0.037037,-0.045787,-0.037037,-0.045787,-0.025950,-0.025950,-0.025950,-0.025950,...,-0.037037,-0.053376,-0.045787,-0.037037,-0.053376,1.000000,-0.025950,-0.037037,-0.053376,-0.045787
"Bot_Move_(9, 6)",NaN,-0.025950,0.700649,-0.032081,-0.025950,-0.032081,-0.018182,-0.018182,-0.018182,-0.018182,...,-0.025950,-0.037398,-0.032081,-0.025950,-0.037398,-0.025950,1.000000,-0.025950,-0.037398,-0.032081
"Bot_Move_(9, 7)",NaN,-0.037037,-0.037037,-0.045787,-0.037037,-0.045787,-0.025950,-0.025950,-0.025950,-0.025950,...,-0.037037,-0.053376,-0.045787,-0.037037,-0.053376,-0.037037,-0.025950,1.000000,-0.053376,-0.045787
"Bot_Move_(9, 8)",NaN,-0.053376,-0.053376,-0.065986,-0.053376,-0.065986,-0.037398,-0.037398,-0.037398,-0.037398,...,-0.053376,-0.076923,-0.065986,-0.053376,-0.076923,-0.053376,-0.037398,-0.053376,1.000000,-0.065986
"Bot_Move_(9, 9)",NaN,-0.045787,-0.045787,-0.056604,-0.045787,1.000000,-0.032081,-0.032081,-0.032081,-0.032081,...,-0.045787,-0.065986,-0.056604,-0.045787,-0.065986,-0.045787,-0.032081,-0.045787,-0.065986,1.000000

TRAIN TEST SPLIT

In [71]:
encoded_data1 = one_hot_encoded_df.copy()
encoded_data2 = label_encoded_df.copy()
raw_data = df.copy()

In [73]:
X = raw_data.drop('Bot_Move', axis=1)
y = raw_data['Bot_Move']

In [74]:
X.head()

   Bot_Cell Crew_Cell  Distance_from_bot_to_crew
0  (10, 10)   (10, 8)                          2
1   (10, 9)    (9, 8)                          2
2    (9, 9)    (9, 7)                          2
3    (9, 8)    (8, 7)                          2
4    (9, 7)    (7, 7)                          2

In [81]:
print(type(y[0]))

<class 'str'>

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

MODELS

In [78]:
model = LogisticRegression()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

ValueError: could not convert string to float: '(6, 8)'