In [1]:
import pandas as pd
import math
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

READ AND PREPROCESS DATA

In [21]:
df =pd.read_csv("output.csv")

In [22]:
df.shape

(2801, 3)

In [23]:
df.head(20)

    Bot_Cell Crew_Cell                                       Closed_Cells
0     (3, 5)   (7, 10)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
1     (3, 6)   (8, 10)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
2     (4, 7)    (8, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
3     (5, 8)    (9, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
4     (6, 9)    (8, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
5    (7, 10)    (9, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
6    (8, 10)   (10, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
7     (9, 9)  (10, 10)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
8    (9, 10)   (10, 9)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
9   (10, 10)   (10, 8)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
10   (10, 9)    (9, 8)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
11    (9, 9)    (9, 7)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
12    (9, 8)   (10, 7)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
13   (10, 8)   (10, 6)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
14   (10, 7)   (10, 5)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
15   (10, 6)    (9, 5)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
16   (10, 5)    (8, 5)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
17    (9, 5)    (7, 5)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
18    (8, 5)    (7, 4)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...
19    (8, 4)    (7, 3)  [(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...

In [24]:
# Extract x, y, p, and q values from the existing columns
df['x'] = df['Bot_Cell'].apply(lambda x: int(x.split(',')[0].strip('()')))
df['y'] = df['Bot_Cell'].apply(lambda x: int(x.split(',')[1].strip('()')))
df['p'] = df['Crew_Cell'].apply(lambda x: int(x.split(',')[0].strip('()')))
df['q'] = df['Crew_Cell'].apply(lambda x: int(x.split(',')[1].strip('()')))

# Calculate the distance
df['Distance_from_bot_to_crew'] = abs(df['x'] - df['p']) + abs(df['y'] - df['q'])
df['Distance_from_bot_to_teleport'] = abs(df['x'] - 5) + abs(df['y'] - 5)
df['Distance_from_crew_to_teleport'] = abs(5 - df['p']) + abs(5 - df['q'])
#Drop the intermediate columns x, y, p, and q if needed
df.drop(['x', 'y', 'p', 'q'], axis=1, inplace=True)

In [25]:
def calculate_angle(point1, point2):
    origin = (5, 5)  # Assuming (5, 5) as the point of origin
    vector1 = (point1[0] - origin[0], point1[1] - origin[1])
    vector2 = (point2[0] - origin[0], point2[1] - origin[1])
    
    dot_product = vector1[0] * vector2[0] + vector1[1] * vector2[1]
    magnitude1 = math.sqrt(vector1[0]**2 + vector1[1]**2)
    magnitude2 = math.sqrt(vector2[0]**2 + vector2[1]**2)
    
    if magnitude1 == 0 or magnitude2 == 0:
        return 0  # Return 0 angle if magnitude is zero
    
    angle_radians = math.acos(dot_product / (magnitude1 * magnitude2))
    angle_degrees = math.degrees(angle_radians)
    
    return angle_degrees

def parse_tuple(string_tuple):
    return tuple(map(int, string_tuple.strip('()').split(',')))

def calculate_angle_for_row(row):
    bot_cell = parse_tuple(row['Bot_Cell'])
    crew_cell = parse_tuple(row['Crew_Cell'])
    return calculate_angle(bot_cell, crew_cell)

In [27]:
#df['Angle'] = df.apply(calculate_angle_for_row, axis=1)

In [28]:
df['Bot_Move'] = df['Bot_Cell'].shift(-1)

In [29]:
def clean_Bot_Move(row, df):
    crew_cell = parse_tuple(row['Crew_Cell'])
    if crew_cell[0] == 5 and crew_cell[1] == 5:
        return None
    else:
        next_row_index = row.name + 1  # Get the index of the next row
        if next_row_index < len(df):
            return df.at[next_row_index, 'Bot_Cell']  # Return Bot_Cell value from the next row

# Assuming parse_tuple function is defined elsewhere
# You need to replace it with your actual implementation

df['Bot_Move'] = df.apply(lambda row: clean_Bot_Move(row, df), axis=1)

In [30]:
df.head()

,Bot_Cell,Crew_Cell,Closed_Cells,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Bot_Move
0,"(3, 5)","(7, 10)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",9,2,7,"(3, 6)"
1,"(3, 6)","(8, 10)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",9,3,8,"(4, 7)"
2,"(4, 7)","(8, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",6,3,7,"(5, 8)"
3,"(5, 8)","(9, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",5,3,8,"(6, 9)"
4,"(6, 9)","(8, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,7,"(7, 10)"

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2801 entries, 0 to 2800
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Bot_Cell                        2801 non-null   object
 1   Crew_Cell                       2801 non-null   object
 2   Closed_Cells                    2801 non-null   object
 3   Distance_from_bot_to_crew       2801 non-null   int64
 4   Distance_from_bot_to_teleport   2801 non-null   int64
 5   Distance_from_crew_to_teleport  2801 non-null   int64
 6   Bot_Move                        2701 non-null   object
dtypes: int64(3), object(4)
memory usage: 153.3+ KB

In [32]:
def parse_coordinates(coord_str):
    if coord_str:
        x, y = map(int, coord_str.strip("()").split(","))
        return x, y
    else:
        return None

def calculate_direction(row):
    bot_cell = parse_coordinates(row['Bot_Cell'])
    bot_move = parse_coordinates(row['Bot_Move'])

    if bot_cell and bot_move:
        delta_x = bot_move[0] - bot_cell[0]
        delta_y = bot_move[1] - bot_cell[1]

        if delta_x == 0 and delta_y == 0:
            return "No movement"
        elif delta_x == 0:
            return "North" if delta_y > 0 else "South"
        elif delta_y == 0:
            return "East" if delta_x > 0 else "West"
        elif delta_x > 0:
            return "Northeast" if delta_y > 0 else "Southeast"
        else:
            return "Northwest" if delta_y > 0 else "Southwest"
    else:
        return "Invalid coordinates"

# Apply the calculate_direction function to each row and store the result in a new column
df['Direction_of_Bot'] = df.apply(lambda row: calculate_direction(row), axis=1)

In [36]:
df["Closed_Cells"][0]

'[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0, 6), (2, 9), (10, 4), (1, 4), (8, 8)]'

In [37]:
def map_coordinates_to_integer_walls(cell):
    cols = 11
    return cell[0] * cols + cell[1] + 1

def apply_map_coordinates_to_integer_walls(row):
    return [map_coordinates_to_integer(cell) for cell in row['Closed_Cells']]

df['Closed_Cells_Integer'] = df.apply(apply_map_coordinates_to_integer_walls, axis=1)

df.head()

KeyError: 'Wall_Cells'

In [34]:
def map_coordinates_to_integer(row,celltype):
    cell = parse_coordinates(row[celltype])
    cols = 11
    return cell[0] * cols + cell[1] + 1

df["Bot_Cell_Encoded"] = df.apply(lambda row: map_coordinates_to_integer(row,"Bot_Cell"), axis=1)
df["Crew_Cell_Encoded"] = df.apply(lambda row: map_coordinates_to_integer(row,"Crew_Cell"), axis=1)
df["Bot_Move_Encoded"] = df.apply(lambda row: map_coordinates_to_integer(row,"Bot_Move"), axis=1)

TypeError: 'NoneType' object is not subscriptable

In [52]:
df['Bot_Move_Encoded'] = df['Bot_Cell_Encoded'].shift(-1)
df.head(60)

,Bot_Cell,Crew_Cell,Closed_Cells,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Bot_Move,Bot_Cell_Encoded,Crew_Cell_Encoded,Bot_Move_Encoded
0,"(3, 5)","(7, 10)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",9,2,7,"(3, 6)",39,88,40.0
1,"(3, 6)","(8, 10)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",9,3,8,"(4, 7)",40,99,52.0
2,"(4, 7)","(8, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",6,3,7,"(5, 8)",52,98,64.0
3,"(5, 8)","(9, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",5,3,8,"(6, 9)",64,109,76.0
4,"(6, 9)","(8, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,7,"(7, 10)",76,98,88.0
5,"(7, 10)","(9, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",3,7,8,"(8, 10)",88,109,99.0
6,"(8, 10)","(10, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",3,8,9,"(9, 9)",99,120,109.0
7,"(9, 9)","(10, 10)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,10,"(9, 10)",109,121,110.0
8,"(9, 10)","(10, 9)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,9,9,"(10, 10)",110,120,121.0
9,"(10, 10)","(10, 8)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,10,8,"(10, 9)",121,119,120.0
10,"(10, 9)","(9, 8)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,9,7,"(9, 9)",120,108,109.0
11,"(9, 9)","(9, 7)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,6,"(9, 8)",109,107,108.0
12,"(9, 8)","(10, 7)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,7,"(10, 8)",108,118,119.0
13,"(10, 8)","(10, 6)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,6,"(10, 7)",119,117,118.0
14,"(10, 7)","(10, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,5,"(10, 6)",118,116,117.0
15,"(10, 6)","(9, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,4,"(10, 5)",117,105,116.0
16,"(10, 5)","(8, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,3,"(9, 5)",116,94,105.0
17,"(9, 5)","(7, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,2,"(8, 5)",105,83,94.0
18,"(8, 5)","(7, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,3,3,"(8, 4)",94,82,93.0
19,"(8, 4)","(7, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,4,"(8, 3)",93,81,92.0
20,"(8, 3)","(7, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,5,"(8, 2)",92,80,91.0
21,"(8, 2)","(7, 1)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,6,"(8, 1)",91,79,90.0
22,"(8, 1)","(7, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,5,"(7, 1)",90,80,79.0
23,"(7, 1)","(8, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,6,"(8, 1)",79,91,90.0
24,"(8, 1)","(9, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,7,"(9, 1)",90,102,101.0
25,"(9, 1)","(10, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,8,"(10, 1)",101,113,112.0
26,"(10, 1)","(9, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,9,7,"(9, 1)",112,102,101.0
27,"(9, 1)","(10, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,8,"(10, 1)",101,113,112.0
28,"(10, 1)","(9, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,9,7,"(9, 1)",112,102,101.0
29,"(9, 1)","(8, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,8,6,"(9, 2)",101,91,102.0
30,"(9, 2)","(8, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,5,"(8, 2)",102,92,91.0
31,"(8, 2)","(9, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,6,"(9, 2)",91,103,102.0
32,"(9, 2)","(9, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,5,"(9, 3)",102,104,103.0
33,"(9, 3)","(8, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,4,"(9, 4)",103,93,104.0
34,"(9, 4)","(8, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,3,"(9, 5)",104,94,105.0
35,"(9, 5)","(8, 6)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,4,"(9, 6)",105,95,106.0
36,"(9, 6)","(8, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,3,"(9, 5)",106,94,105.0
37,"(9, 5)","(8, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,4,"(9, 4)",105,93,104.0
38,"(9, 4)","(7, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,3,"(8, 4)",104,82,93.0
39,"(8, 4)","(7, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,4,"(8, 3)",93,81,92.0
40,"(8, 3)","(7, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,5,"(8, 2)",92,80,91.0
41,"(8, 2)","(7, 1)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,6,"(8, 1)",91,79,90.0
42,"(8, 1)","(7, 0)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,7,"(7, 1)",90,78,79.0
43,"(7, 1)","(6, 0)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,6,"(7, 0)",79,67,78.0
44,"(7, 0)","(6, 1)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,7,5,"(7, 1)",78,68,79.0
45,"(7, 1)","(5, 1)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,6,4,"(6, 1)",79,57,68.0
46,"(6, 1)","(4, 1)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,5,"(5, 1)",68,46,57.0
47,"(5, 1)","(4, 2)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,4,"(4, 1)",57,47,46.0
48,"(4, 1)","(4, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,5,3,"(4, 2)",46,48,47.0
49,"(4, 2)","(5, 3)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,4,2,"(5, 2)",47,59,58.0
50,"(5, 2)","(5, 4)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,3,1,"(5, 3)",58,60,59.0
51,"(5, 3)","(5, 5)","[(1, 9), (4, 0), (1, 10), (10, 3), (8, 0), (0,...",2,2,0,None,59,61,29.0
52,"(2, 6)","(7, 7)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",6,4,4,"(3, 7)",29,85,41.0
53,"(3, 7)","(7, 8)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",5,4,5,"(4, 8)",41,86,53.0
54,"(4, 8)","(7, 9)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",4,4,6,"(5, 9)",53,87,65.0
55,"(5, 9)","(8, 9)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",3,4,7,"(6, 9)",65,98,76.0
56,"(6, 9)","(9, 9)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",3,5,8,"(7, 9)",76,109,87.0
57,"(7, 9)","(8, 9)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",1,6,7,"(8, 10)",87,98,99.0
58,"(8, 10)","(8, 8)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",2,8,6,"(8, 9)",99,97,98.0
59,"(8, 9)","(9, 8)","[(3, 3), (3, 9), (9, 6), (8, 7), (4, 0), (0, 0...",2,7,7,"(9, 9)",98,108,109.0

In [16]:
df['Pre_Distance_between_Encoding'] = abs(df["Bot_Cell_Encoded"] - df["Crew_Cell_Encoded"])
df['Post_Distance_between_Encoding'] = abs(df["Bot_Move_Encoded"] - df["Crew_Cell_Encoded"])

Encodding the data

In [17]:
one_hot_encoded_df = df.copy()
one_hot_encoded_df = pd.get_dummies(df)
one_hot_encoded_df.head()

,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Angle,Bot_Cell_Encoded,Crew_Cell_Encoded,Bot_Move_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding,"Bot_Cell_(0, 0)",...,Direction_of_Bot_East,Direction_of_Bot_Invalid coordinates,Direction_of_Bot_No movement,Direction_of_Bot_North,Direction_of_Bot_Northeast,Direction_of_Bot_Northwest,Direction_of_Bot_South,Direction_of_Bot_Southeast,Direction_of_Bot_Southwest,Direction_of_Bot_West
0,12,5,7,176.820170,36,98,48.0,62,50.0,False,...,False,False,False,False,True,False,False,False,False,False
1,11,3,8,175.601295,48,99,60.0,51,39.0,False,...,False,False,False,False,True,False,False,False,False,False
2,8,1,7,143.130102,60,98,72.0,38,26.0,False,...,False,False,False,False,True,False,False,False,False,False
3,7,1,8,45.000000,72,109,84.0,37,25.0,False,...,False,False,False,False,True,False,False,False,False,False
4,6,3,9,12.094757,84,120,96.0,36,24.0,False,...,False,False,False,False,True,False,False,False,False,False

In [18]:
label_encoder = LabelEncoder()
label_encoded_df = df.copy()
if label_encoded_df["Direction_of_Bot"].dtype == 'object':
    label_encoded_df["Direction_of_Bot"] = label_encoder.fit_transform(label_encoded_df["Direction_of_Bot"])

In [19]:
label_encoded_df.head(10)

,Bot_Cell,Crew_Cell,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Bot_Move,Angle,Direction_of_Bot,Bot_Cell_Encoded,Crew_Cell_Encoded,Bot_Move_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding
0,"(3, 2)","(8, 9)",12,5,7,"(4, 3)",176.820170,4,36,98,48.0,62,50.0
1,"(4, 3)","(8, 10)",11,3,8,"(5, 4)",175.601295,4,48,99,60.0,51,39.0
2,"(5, 4)","(8, 9)",8,1,7,"(6, 5)",143.130102,4,60,98,72.0,38,26.0
3,"(6, 5)","(9, 9)",7,1,8,"(7, 6)",45.000000,4,72,109,84.0,37,25.0
4,"(7, 6)","(10, 9)",6,3,9,"(8, 7)",12.094757,4,84,120,96.0,36,24.0
5,"(8, 7)","(10, 10)",5,5,10,"(8, 8)",11.309932,3,96,121,97.0,25,24.0
6,"(8, 8)","(10, 9)",3,6,9,"(9, 8)",6.340192,0,97,120,108.0,23,12.0
7,"(9, 8)","(9, 9)",1,7,8,"(10, 9)",8.130102,4,108,109,120.0,1,11.0
8,"(10, 9)","(8, 9)",2,9,7,"(9, 9)",14.470294,9,120,98,109.0,22,11.0
9,"(9, 9)","(7, 9)",2,8,6,"(8, 9)",18.434949,9,109,87,98.0,22,11.0

Scalling the data

In [20]:
label_encoded_df = label_encoded_df.drop('Bot_Cell',axis =1)
label_encoded_df = label_encoded_df.drop('Crew_Cell',axis =1)
label_encoded_df = label_encoded_df.drop('Bot_Move',axis =1)

In [21]:
label_encoded_df.head()

,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Angle,Direction_of_Bot,Bot_Cell_Encoded,Crew_Cell_Encoded,Bot_Move_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding
0,12,5,7,176.820170,4,36,98,48.0,62,50.0
1,11,3,8,175.601295,4,48,99,60.0,51,39.0
2,8,1,7,143.130102,4,60,98,72.0,38,26.0
3,7,1,8,45.000000,4,72,109,84.0,37,25.0
4,6,3,9,12.094757,4,84,120,96.0,36,24.0

In [22]:
correlation_matrix2 = label_encoded_df.corr()

In [23]:
correlation_matrix2

,Distance_from_bot_to_crew,Distance_from_bot_to_teleport,Distance_from_crew_to_teleport,Angle,Direction_of_Bot,Bot_Cell_Encoded,Crew_Cell_Encoded,Bot_Move_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding
Distance_from_bot_to_crew,1.000000,-0.026863,0.277615,0.848174,0.091888,-0.045288,0.051928,-0.037197,0.759653,0.679990
Distance_from_bot_to_teleport,-0.026863,1.000000,0.530905,-0.157671,0.046591,-0.000615,-0.002880,-0.002930,-0.032144,-0.143897
Distance_from_crew_to_teleport,0.277615,0.530905,1.000000,0.196932,0.116340,0.007286,0.045057,0.019520,0.208141,0.066678
Angle,0.848174,-0.157671,0.196932,1.000000,0.118018,-0.035044,0.042227,-0.026055,0.657336,0.557210
Direction_of_Bot,0.091888,0.046591,0.116340,0.118018,1.000000,0.198255,-0.095022,0.003054,0.072902,-0.010678
Bot_Cell_Encoded,-0.045288,-0.000615,0.007286,-0.035044,0.198255,1.000000,0.808940,0.943999,-0.034652,-0.043288
Crew_Cell_Encoded,0.051928,-0.002880,0.045057,0.042227,-0.095022,0.808940,1.000000,0.871499,0.052164,0.041011
Bot_Move_Encoded,-0.037197,-0.002930,0.019520,-0.026055,0.003054,0.943999,0.871499,1.000000,-0.024405,-0.041772
Pre_Distance_between_Encoding,0.759653,-0.032144,0.208141,0.657336,0.072902,-0.034652,0.052164,-0.024405,1.000000,0.783605
Post_Distance_between_Encoding,0.679990,-0.143897,0.066678,0.557210,-0.010678,-0.043288,0.041011,-0.041772,0.783605,1.000000

In [24]:
label_encoded_df = label_encoded_df.drop("Distance_from_bot_to_teleport",axis=1)
label_encoded_df = label_encoded_df.drop("Distance_from_crew_to_teleport",axis=1)

TRAIN TEST SPLIT

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [26]:
final_data = label_encoded_df.copy()
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6047 entries, 0 to 6046
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Distance_from_bot_to_crew       6047 non-null   int64
 1   Angle                           6047 non-null   float64
 2   Direction_of_Bot                6047 non-null   int32
 3   Bot_Cell_Encoded                6047 non-null   int64
 4   Crew_Cell_Encoded               6047 non-null   int64
 5   Bot_Move_Encoded                6046 non-null   float64
 6   Pre_Distance_between_Encoding   6047 non-null   int64
 7   Post_Distance_between_Encoding  6046 non-null   float64
dtypes: float64(3), int32(1), int64(4)
memory usage: 354.4 KB

In [27]:
final_data = final_data.dropna()

In [28]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6046 entries, 0 to 6045
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Distance_from_bot_to_crew       6046 non-null   int64
 1   Angle                           6046 non-null   float64
 2   Direction_of_Bot                6046 non-null   int32
 3   Bot_Cell_Encoded                6046 non-null   int64
 4   Crew_Cell_Encoded               6046 non-null   int64
 5   Bot_Move_Encoded                6046 non-null   float64
 6   Pre_Distance_between_Encoding   6046 non-null   int64
 7   Post_Distance_between_Encoding  6046 non-null   float64
dtypes: float64(3), int32(1), int64(4)
memory usage: 401.5 KB

In [29]:
X = final_data.drop('Bot_Move_Encoded', axis=1)
y = final_data['Bot_Move_Encoded']

In [30]:
X.head()

,Distance_from_bot_to_crew,Angle,Direction_of_Bot,Bot_Cell_Encoded,Crew_Cell_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding
0,12,176.820170,4,36,98,62,50.0
1,11,175.601295,4,48,99,51,39.0
2,8,143.130102,4,60,98,38,26.0
3,7,45.000000,4,72,109,37,25.0
4,6,12.094757,4,84,120,36,24.0

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train

,Distance_from_bot_to_crew,Angle,Direction_of_Bot,Bot_Cell_Encoded,Crew_Cell_Encoded,Pre_Distance_between_Encoding,Post_Distance_between_Encoding
3948,2,14.036243,9,13,3,10,1.0
1094,2,0.000000,6,66,64,2,1.0
1121,8,109.653824,7,42,106,64,54.0
1770,2,18.434949,0,47,59,12,1.0
4857,2,18.434949,6,91,79,12,11.0
...,...,...,...,...,...,...,...
3772,2,22.619865,6,92,80,12,11.0
5191,2,19.653824,0,96,106,10,1.0
5226,2,1.789911,0,2,14,12,1.0
5390,2,4.398705,3,23,35,12,11.0
860,2,18.434949,0,15,37,22,11.0

MODELS

LINEAR REGRESSION

In [34]:
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 70.45784155092373